name: Hello World!

on:
  push:
    branches:
      - "master"

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Hello
        run: |
          echo "Hello world"
      - name: Date
        run: date
      - name: Directory content
        run: ls -l

